### ISSUE TITLE
AWS Lambda TypeError:

### ISSUE THREAD

**Issue by srpeltz** [sqren/await-sleep#1]
I'm currently using this and when I deploy to AWS it gives me this response. Currently working in an asynchronous typescript environment. 

`   TypeError: await_sleep_1.default is not a function
       at Object.<anonymous> (/var/task/src/service/Customer.js:41:36)
       at next (native)
       at fulfilled (/var/task/src/service/Customer.js:4:58)
       at process._tickDomainCallback (internal/process/next_tick.js:135:7) }`

It's imported like so `import sleep from 'await-sleep'` and put in my service function like so `await sleep(1500);`

thanks!

**Comment by fider** [comment]
Hi for anyone who met this problem, just change your import to `import * as sleep from 'await-sleep'.

(to solve this problem it is enough to check node_modules/await-sleep/index.js).

@sqren update docs for tsc 3.0 and close

**Comment by sorenlouv** [comment]
Done. Thanks for the tip. I guess the better solution is to distribute the module in different formats.
