### ISSUE TITLE
Blocking vs non-blocking

### ISSUE THREAD

**Issue by chrisshiplet** [sqren/await-sleep#2]
Thanks for the nifty package!

I noticed in the README you describe it as a "blocking" sleep, but as far as I can tell, that isn't the case? It's kind of a nit-pick, but when it comes to sleeping in Node APIs it's a pretty important distinction. This will certainly block the function where it's used from continuing until the promise resolves, but the event loop will continue handling other requests. Here's a demo:

**Non-blocking sleep**

```
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

async function sleepThenLog() {
  await sleep(5000);
  console.log('slept for 5000ms');
}

async function immediatelyLog() {
  console.log('no sleep at all');
}

sleepThenLog();
immediatelyLog();
```

Returns:

`no sleep at all`
_...5000ms delay_
`slept for 5000ms`

**Blocking sleep** (requires node 9.3+)

```
async function sleepThenLog() {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 5000)
  console.log('slept for 5000ms');
}

async function immediatelyLog() {
  console.log('no sleep at all');
}

sleepThenLog();
immediatelyLog();
```

Returns (after 5000ms):

`slept for 5000ms`
`no sleep at all`

**Comment by milankubin** [comment]
You have to do wrap the whole thing in an async function then
await sleepThenLog();
Otherwise it won't block because the functions are ran in parallel.

**Comment by sorenlouv** [comment]
@chrisshiplet True, it's not blocking. I've updated the readme to make it clear.
